[package]
name = "msm-benches"
version = "0.1.0"
edition = "2021"

[dependencies]
blst = "0.3.11"
rust-kzg-blst = { path = "../blst", default-features = false, features = ["std", "rand"] }
kzg = { path = "../kzg" }
rand = "0.8.5"
rand_chacha = "0.3"

[dev-dependencies]
criterion = "0.5.1"

[features]
wbits = ["rust-kzg-blst/wbits"]
grigaitis_pairwise = ["rust-kzg-blst/grigaitis_pairwise"]
grigaitis_pairwise_booth = ["rust-kzg-blst/grigaitis_pairwise_booth"]
grigaitis_pairwise_cpdlh = ["rust-kzg-blst/grigaitis_pairwise_cpdlh"]
parallel = ["rust-kzg-blst/parallel"]

[[bench]]
name = "g1_fixed_base_msm"
harness = false
