[package]
name = "rust-kzg-mcl-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-kzg-mcl = { path = '../kzg' }
blst = {'git' = 'https://github.com/supranational/blst.git'}
kzg = { path = "../../kzg" }
kzg-bench = { path = "../../kzg-bench" }

[dev-dependencies]
rand = "0.8.5"
criterion = "0.5.1"

[features]
minimal-spec = ["kzg/minimal-spec", "kzg-bench/minimal-spec"]

[[bench]]
name = "shared_fk20"
harness = false

[[bench]]
name = "shared_zero_poly"
harness = false

[[bench]]
name = "shared_fft"
harness = false

[[bench]]
name = "shared_poly"
harness = false

[[bench]]
name = "shared_das"
harness = false

[[bench]]
name = "shared_recover"
harness = false

[[bench]]
name = "shared_kzg_proof"
harness = false

[[bench]]
name = "shared_eip_4844"
harness = false

[[bench]]
name = "shared_lincomb"
harness = false
