name: arkworks tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: "[arkworks] Tests (minimal preset)"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast --test eip_4844 tests --features minimal-spec

      - name: "[arkworks] Tests (mainnet preset)"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast

      - name: "[arkworks] Tests (mainnet preset, parallel)"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast --features parallel

      - name: "[arkworks] Clippy"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --manifest-path arkworks/Cargo.toml --all-targets --all-features -- -D warnings

      - name: "[arkworks] Formatting"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --manifest-path arkworks/Cargo.toml -- --check

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --manifest-path kzg-bench/Cargo.toml -- --check
